[package]
name = "massa_final_state"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
thiserror = "1.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# custom modules
massa_ledger = { path = "../massa-ledger" }
massa_models = { path = "../massa-models" }

[dev-dependencies]
pretty_assertions = "1.0"
serial_test = "0.6"
massa_ledger = { path = "../massa-ledger", features=["testing"] }

[features]
testing = []
