[workspace]
members = [
  "massa-api",
  "massa-bootstrap",
  "massa-client",
  "massa-consensus-exports",
  "massa-consensus-worker",
  "massa-execution-exports",
  "massa-execution-worker",
  "massa-graph",
  "massa-hash",
  "massa-logging",
  "massa-models",
  "massa-network-worker",
  "massa-network-exports",
  "massa-node",
  "massa-sdk",
  "massa-pool",
  "massa-proof-of-stake-exports",
  "massa-protocol-exports",
  "massa-protocol-worker",
  "massa-signature",
  "massa-time",
  "massa-wallet",
  "massa-ledger",
  "massa-final-state"
]
resolver = "2"

# From https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[profile.dev.package."*"]
opt-level = 3 # Speed-up the CI
